env:
  global:
    - JRUBY_OPTS="$JRUBY_OPTS --debug"
language: ruby
script: bundle exec rspec
matrix:
  include:
    - rvm: 1.8.7
      gemfile: gemfiles/ruby-1.8.7.gemfile
    - rvm: 1.9.3
      gemfile: Gemfile
    - rvm: 2.0.0
      gemfile: Gemfile
    - rvm: 2.1
      gemfile: Gemfile
    - rvm: 2.2
      gemfile: Gemfile
    - rvm: 2.3.0
      gemfile: Gemfile
    - rvm: jruby-18mode
      gemfile: gemfiles/ruby-1.8.7.gemfile
    - rvm: jruby-19mode
      gemfile: Gemfile
    - rvm: jruby-head
      gemfile: Gemfile
    - rvm: rbx-2.0
      gemfile: Gemfile
    - rvm: ruby-head
      gemfile: Gemfile
  allow_failures:
    - rvm: 1.8.7
    - rvm: jruby-18mode
    - rvm: jruby-head
    - rvm: rbx-2
    - rvm: ruby-head
  fast_finish: true
sudo: false
