env:
  global:
    - JRUBY_OPTS="$JRUBY_OPTS --debug"
language: ruby
script: bundle exec rspec
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - 2.1
  - 2.2
  - 2.3.0
  - jruby-18mode
  - jruby-19mode
  - jruby-head
  - rbx-2
  - ruby-head
gemfile:
  - Gemfile
  - gemfiles/ruby-1.8.7.gemfile
matrix:
  exclude:
    - rvm: 1.8.7
      gemfile: Gemfile
    - rvm: jruby-18mode
      gemfile: Gemfile
    - rvm: 2.0.0
      gemfile: gemfiles/ruby-1.8.7.gemfile
    - rvm: 2.1
      gemfile: gemfiles/ruby-1.8.7.gemfile
    - rvm: 2.2
      gemfile: gemfiles/ruby-1.8.7.gemfile
    - rvm: 2.3.0
      gemfile: gemfiles/ruby-1.8.7.gemfile
    - rvm: jruby-19mode
      gemfile: gemfiles/ruby-1.8.7.gemfile
    - rvm: jruby-head
      gemfile: gemfiles/ruby-1.8.7.gemfile
    - rvm: rbx-2.0
      gemfile: gemfiles/ruby-1.8.7.gemfile
    - rvm: ruby-head
      gemfile: gemfiles/ruby-1.8.7.gemfile
  allow_failures:
    - rvm: 1.8.7
    - rvm: jruby-18mode
    - rvm: jruby-head
    - rvm: rbx-2
    - rvm: ruby-head
  fast_finish: true
sudo: false
